version: '2'
services:
  cassandra1:
    image: cassandra
    volumes:
      - ./tmp/db1:/var/lib/cassandra
    ports:
      - "9042:9042"
    expose:
      - 9042

  cassandra2:
    image: cassandra
    volumes:
      - ./tmp/db2:/var/lib/cassandra
    ports:
      - "9142:9042"
    expose:
      - 9142

  redis:
    image: redis
    volumes:
      - ./tmp/redis:/var/lib/redis/data
    expose:
      - 6379

  proxy:
    build: ./proxy
    volumes:
      - ./proxy:/myapp
    ports:
      - "9292:9292"
    expose:
      - 9292
    depends_on:
      - redis
    environment:
      - PROXY_PORT=9292
    restart:
      "always"
    links:
      - "warehouse"

  warehouse:
    build: ./warehouse
    volumes:
      - ./warehouse:/myapp
    expose:
      - 9191
    depends_on:
      - cassandra1
      - cassandra2
    environment:
      - WAREHOUSE_PORT=9191
    restart:
      "always"
