version: '2'
services:
  cassandra:
    image: cassandra
    volumes:
      - ./tmp/db:/var/lib/cassandra/data

  redis:
    image: redis
    volumes:
      - ./tmp/redis:/var/lib/redis/data

  proxy:
    build: ./proxy
    ports:
      - "9292:9292"
    expose:
      - "9292"
    depends_on:
      - redis
    environment:
      - PROXY_PORT=9292

  warehouse:
    build: ./warehouse
    ports:
      - "9191:9191"
    expose:
      - "9191"
    depends_on:
      - cassandra
    environment:
    - WAREHOUSE_PORT=9191
