version: '2'
services:
  cassandra:
    image: cassandra
    volumes:
      - ./tmp/db:/var/lib/cassandra/data

  redis:
    image: redis
    volumes:
      - ./tmp/redis:/var/lib/redis/data
    expose:
      - 6379

  proxy:
    build: ./proxy
    volumes:
      - ./proxy:/myapp
    ports:
      - "9292:9292"
    expose:
      - "9292"
    depends_on:
      - redis
    environment:
      - PROXY_PORT=9292
    restart:
      "always"
    links:
      - "warehouse"

  warehouse:
    build: ./warehouse
    volumes:
      - ./warehouse:/myapp
    expose:
      - "9191"
    depends_on:
      - cassandra
    environment:
    - WAREHOUSE_PORT=9191
    restart:
      "always"